apiVersion: v1
kind: Service
metadata:
  name: gallery-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: gallery-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gallery-backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
