---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: plants-staging
spec:
  encryptedData:
    .dockerconfigjson: AgB8BxNhPt2j9cylU5PnDCQcJEBTOrOQiK+E0qWXdjotoOhUXK9S03KVB7dEZFd/QoKc6IrSR3UvkcreZUlcsrUbTvqAgkFwJPRX7SHYHlqRveJPOImRlzqV2ygQi6j53Z79Hh4Eoxd9EfAhS8I8NeWHziEha7p9/REGjJj5kWTe2DwUxUYaRZgUlGyDB00f4rOVYFA4kc+Fvz3UBwqAgiNjjzyAJvwWi0TS2I1qWbwzCEg2UdyX+wX2dqCn8oHu9FM0Y5GakZq1hb2rQ2WuzuaAQegh+8vV+cKfBGRLI6WrcepgDEgPwUiT3/cwJ5Qdl+thrO4wDOIip8+AfU9WfHFa1UUVCMoJlHXubdrXgISqy/O37+U8MmqUR0NnlXSP+cCool/yrAlxB6kMzMQfFYTcdzfGftDblHv0OoKKFeje+dEwzXZDVckWF52sr9vW58TrPAH297XGRaZNWm8thcx9ZDkGrQzVNLYMFnfQDF8dCDwgIECeT/mT8OAJJ9g8pqu2CsJs2wvVqXGun2ucwPsjrQVMx4onwikZpnGWw+QbzM8I8f8cl8MGF7tYpIdmOY9/j+IYcfQXUoEUMjQ5yAJJy6voQrYb0Lnc9f1WaLW0FzwYUkXSCMy2WiXb65fpW6flKXDrry0EVe9r2Wxusc5aEh1FFuebdcKwY259NdH6Ub32GBGqRzeL1saZIqgdP4On/P5QZZC1BitQbGoQfQkxVhnYuj183Le9QH1YeLjXjNs1e0IvR3yaoa6N6F0OAmVwWLEiOiIOMXoOkTHE4BoyZ9gVMReJzmn2U/m4M4sLV8IBQZ2xGotwdob00hK7LmvK04AI7sys5zcuGX/aByxa15vazWHHr3J9Dzbvkb8EJSuFVzw=
  template:
    metadata:
      name: registry-credentials
      namespace: plants-staging
    type: kubernetes.io/dockerconfigjson
