---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: plants
spec:
  encryptedData:
    .dockerconfigjson: AgBrdW8HLgynqLizaHcw9VxJXxqBah4kXblDq86eaaQ6dgDpNK/TZE9j19n73XvCG5gzpKWIA9MLSvP56ddHLB7yHXdYWGx8r1ueFb0Ct/IOYAIhwxyIxQTgeo8vSE41LUnSillhLKxPwX3UK2XMXxP49nUGKP1RgiiUQGC8+7OVAcqitr/kl1geGT/2j0nS9FGJQlR410z/PFnzfE0ql+HsrFb51Hk167KJAD9KUEZzx+VVS3rFtzk1pP+rFbdUj+DSbvSRH+9mYHI+DLJAdG9HZRtY4WS3t15dv26KN+NG8BHFVzp73uOB+Gk3iaNiQKtV0wRhSmLR51SF9vpclCO0dyl5MV9lX+3VjH+ReHt9zp9BpaXgldCZs+ppIkb2OIUmmF2WneOQG75oRfOnGjA8m6F5sJyk8aVawffk4zXeuXaFqLaijt1JEe+VKO18VdEvAx0Pt2uY08NelDCzpVsK0UiCwC92lieMmxu4teR18OvGnc7wutmySmabBzkGZXzXxMyFLWaUJooAA3PNdEWpfwsj3S5BNi8cPNJVWCaB0gQzRmsc5lpFueZ+s6t8Ii5GsLJff+7j+OchvpTqGwjCKAjY2KGg/MhG5Sqg+AMFz1AW9fkT4NCbfCDU5s6GtNneTo/GgZA1N+DXNOt3XbWRNKPdXdKzxHb4cn2BR1XP50A55T3FE4INCKbSoFzwlpm6b1t0B+ALKv6Nwtp3uHr3ruP0oBKfUoraX19o0D14dxrpGBFy968LpGbPL8nolcczzUfFtQd+liQIycoT7/hjWPiOjoJdJbz9ZM/0J71gca8esgFY7FNMFQDjHS+pwScKjJromHMQtWsyB4R4i3ghONxXPkBV4TUEhFoXZ57TDvjvGm4=
  template:
    metadata:
      name: registry-credentials
      namespace: plants
    type: kubernetes.io/dockerconfigjson
