replicaCount: 1

image:
  repository: registry.boukingolts.dev/plants-backend
  # Updated automatically by Argo Workflows on each push to dev
  tag: "0e9936e"
  pullPolicy: Always

registry:
  enabled: true
  url: "registry.boukingolts.dev"

service:
  type: ClusterIP
  port: 5000

ingress:
  host: staging.api.boukingolts.dev

env:
  BASE_URL: "https://staging.boukingolts.dev"
  API_URL: "https://staging.api.boukingolts.dev"
  S3_ENDPOINT_URL: "https://axmemlyrscvh.compat.objectstorage.il-jerusalem-1.oraclecloud.com"
  S3_BUCKET: "images"
  S3_REGION: "il-jerusalem-1"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
