replicaCount: 1

image:
  repository: registry.boukingolts.dev/plants-frontend
  # Updated automatically by Argo Workflows on each push to dev
  tag: "b303733"
  pullPolicy: Always

registry:
  enabled: true
  url: "registry.boukingolts.dev"

service:
  type: ClusterIP
  port: 3000

ingress:
  host: staging.boukingolts.dev

env:
  apiUrl: http://backend:5000

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
