replicaCount: 1

image:
  repository: ghcr.io/yevgenio/plants-frontend
  # Updated automatically by GitHub Actions on each push to dev
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  host: staging.boukingolts.dev

env:
  apiUrl: http://backend:5000

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
