apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plants-backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yevgenio/plants-cluster
    targetRevision: HEAD
    path: manifests/plants-backend-staging
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plants-backend-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
