apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yevgenio/plants-cluster
    targetRevision: HEAD
    path: manifests/registry
    helm:
      releaseName: registry
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
