---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-secrets
  namespace: argo
spec:
  encryptedData:
    GITOPS_TOKEN: AgBmjcThh+jkjM5thzQhy/+kw52r48Co8X8SajiQdyRJ809mMKticuZo5uMJEOnaT9+7wZvjVnrq3qB7K9CdRtLTNVvq48bN/dkTYzbSxH/4+0j4pDf5H47gjIR0PnIQAkiyNFyCvtq702myh4qUgtFsM1IAoD5FD44ZkS5hdLVIgjATbahF6lTO90UFdTjdsDrc4WO90fJtUpyxHXEHFx+URtHviEAGpxurIUF9hzZnCkpAtk8On4bOcvi9aZk9AY+CIFbSg3XjEXSUxOLylyjPlPxYpP2DqcjPEOtZXVPvusni5KuoHYM2GYbE2FLHEc7C3EeX898h/AjVWIpnC5G9xK/+3Hi+6SNZNhFiJte7yLG9772P3kqlyL2v1OrpvVoM0yaRmY9VQtPgYVPESpvjotjX1ik+C/0c5zlFBiS1Q0xJ4LS5rAs6Dbum8KQq1BGnsaqGxFCn4Y58nKEW4qBmju8rO5yAkx3572hHACNxwKJzB90E9YSbNvZu+dHeIXHqyYRq25ePB9ckEIdFytUK2JdCsToTozrRj6r47YTcdRZQ6hmWfqv7ZjNKopnCI1vx8vghTNMLlt0Mq2S0s9+4TK/+Kt52xAugH7IuokYbRN+mCYnFL2T0ReZHSOA6BDb0LG7MgFowbs9sMge8j25kQw3DNUjMCW9O/8A6rqXbPz5oafmZFZmhy83lh2XI3loFtLtTShykUhQlN/nu73C+60ueHwZF2yp1Rot+bFp7qqr8UQRQb7YjyN5fCA5Lp484FszhWwx+5uZz3rzRfNVWAApBGiv7hhggQxcOrVqPmV8h1DLP2Tb7YEz8TRk=
    WEBHOOK_SECRET: AgA5DQz4tPHyI9gCYQk+bzJbiCKFzx4hc4vMKvb6Fc8q336qr7TRTYneBPaja9tIAjF+CnmULZAD8Nx4+a3gJgVYNgqFeNstc2WW4p1AAjqHZVDWTrHzZkRfpk+h2j+78bMTjKAEIai0CbFJmInzgSoHj/4JPoGu9ai7fAH2rO4IJ75DIzAewNaTQg9+SdKLwlQwAy0zd3/M+iJ6ARWsaku8aS/G0soMTM0sqDmH66zFJxBkL5BlI2VidNZeBqYIWFdmP02Q4NJKFbRlcKO7z2fWWKDssvS2gxOB9NNCX6zUUPnog5FIrmB6RMWQ2SKxwkBKVYEtD31N9uAPOBW7JYoSuJrU95RstR5eBIW0k9hBXuw28gvlDIqI/MygMK+Vcx7M0POrTrx3fRbSHgr0mSXdNsWJn2xuU/h1uBpIVN1u4Mwb7F4WPRMdvFCTML4IEUZguQSCb93sSTjJZOA5p/SRlDOggGngup5KwOGbaJau0bg1ueF9pcXGQ1etfYwSTTYIpe9onijWx+OEilc1QwzxgXXEASzrUmCjr+HBe/WC1pBbzpeaJK4RVNHEh8C99U2gSHtezRdThQgQFB2hCh470axtAEpYiW9U6I8XOTNtrU2UwLCbqAR18IOS/itVJE5fRLGS4YpSkGlAZn/bL/IfVKtgsWOXU/oNm19oDS79pKxqXSyFI/1zsfk3srl32winjsas5qregWx1MLnh/hAuS8mYXRZhP2TJsZ8dt7RWpn6kNKRfRMZE
  template:
    metadata:
      name: argo-secrets
      namespace: argo
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-push-creds
  namespace: argo
spec:
  encryptedData:
    .dockerconfigjson: AgCBRCgyZ3aTPv0axwU7xsQSP+WTm8qMQKKhN9i7fl291bkmeCYR9tSXSeKZpgPP+UTDlmRWHPrw/un+O/cSk8ZDxRGHosUiyGq5uTdlcHnPHxTlcaYgFRBPJuYB7LiM/rwXFtcKZiYbv7RIm9FhoORnbcxUhzGKDkbUsLP7lfzR7nfF6tq7NSVJ/X+f6qKbfNouBB/LiVhrvwJj+6KvCZkt5i49Qx/PxXlqc+lVoKqGmuk87wboX0vlxVy+e9+l/452E35SDYntsgYwEOTN0YQIhwJVWDBW4QZWxkcKTVcxhmSVds6No8QWnFZR2RFGi0GCUfoDneADl9KhQDcJFMpgHWe2O61uvDfCLS47l3ttTZVW2uIArkfc1elWuEHFvN+y1ngu1FPn+OmwBxIfwKpHnhdGw6WYLGMurRNs2ma4VcUC836yFbwXm4hST7TyM4/9RdS6DTbPmdAXCRugkZ23Kb8Ia1XgEntTxAvMNaqG9XDb/6itW0KF3HAcs/ZRD1NmYu2Xi4UzibMX8a+Bd0dhlKghkI/6r/4dpsQKay5TScLrBvQr0+U4nQitutu1dN4w/rks3N8OF2c83TcvPqAORAzOdJjuq4JlIcu8dnaC+OGXT95RXCqaUlOI5syYlX2OHXl3dTzBQkRvtCBInSFtmHPmcprLsOCj5zKMlvq+SuKJXOeAoMDJhhnJXIYrR/Vd1dG7f0crnUk5Ta3xOtELCUjMGZnPo59Zlsv2w9mBAyotKjq1PAXHYB/N05feFWGfZ6kaevoxE8Ujd0hmIKvnReRpcfNacrM4JC194mDUEeq8+yeYw+1A1BBOhYAbJfuvWYtydpaIlcR7xlxHsMMDSoUR7XSa/gCwnJwigFIHERM3IHQ=
  template:
    metadata:
      name: registry-push-creds
      namespace: argo
    type: kubernetes.io/dockerconfigjson
